-- Sequences
CREATE SEQUENCE IF NOT EXISTS SEQ_TUTOR          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CLINICA        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PET            START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EVENTO_CLINICO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROTOCOLO      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MEDICAMENTO    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ADESAO         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_NOTIFICACAO    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_SCORE_HIST     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_BCS_HIST       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_COLLAR         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ALERTA         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_LOG_ERRO       START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_LOG_ERRO (
    ID_LOG        BIGINT         NOT NULL DEFAULT nextval('SEQ_LOG_ERRO'),
    NM_PROCEDURE  VARCHAR(100)   NOT NULL,
    NM_USUARIO    VARCHAR(100)   NOT NULL,
    DT_OCORRENCIA TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CD_ERRO       BIGINT         NOT NULL,
    DS_MENSAGEM   VARCHAR(4000),
    CONSTRAINT TB_LOG_ERRO_PK PRIMARY KEY (ID_LOG)
);

CREATE TABLE IF NOT EXISTS TB_TUTOR (
    ID_TUTOR    BIGINT         NOT NULL DEFAULT nextval('SEQ_TUTOR'),
    NM_TUTOR    VARCHAR(150)   NOT NULL,
    DS_EMAIL    VARCHAR(200)   NOT NULL,
    NR_TELEFONE VARCHAR(20),
    DS_ENDERECO VARCHAR(300),
    DT_CADASTRO TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TB_TUTOR_PK       PRIMARY KEY (ID_TUTOR),
    CONSTRAINT TB_TUTOR_EMAIL_UN UNIQUE      (DS_EMAIL)
);

CREATE TABLE IF NOT EXISTS TB_CLINICA (
    ID_CLINICA  BIGINT         NOT NULL DEFAULT nextval('SEQ_CLINICA'),
    NM_CLINICA  VARCHAR(200)   NOT NULL,
    NR_CNPJ     VARCHAR(18)    NOT NULL,
    DS_EMAIL    VARCHAR(200),
    NR_TELEFONE VARCHAR(20),
    DS_ENDERECO VARCHAR(300),
    DT_CADASTRO TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TB_CLINICA_PK      PRIMARY KEY (ID_CLINICA),
    CONSTRAINT TB_CLINICA_CNPJ_UN UNIQUE      (NR_CNPJ)
);

CREATE TABLE IF NOT EXISTS TB_PET (
    ID_PET        BIGINT        NOT NULL DEFAULT nextval('SEQ_PET'),
    NM_PET        VARCHAR(100)  NOT NULL,
    DS_ESPECIE    VARCHAR(50)   NOT NULL,
    DS_RACA       VARCHAR(100),
    DS_SEXO       CHAR(1),
    NR_IDADE_ANOS NUMERIC(3,1),
    NR_PESO_KG    NUMERIC(6,3),
    DT_CADASTRO   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ID_TUTOR      BIGINT        NOT NULL,
    ID_CLINICA    BIGINT        NOT NULL,
    CONSTRAINT TB_PET_PK      PRIMARY KEY (ID_PET),
    CONSTRAINT CK_PET_SEXO    CHECK (DS_SEXO IN ('F','M')),
    CONSTRAINT FK_PET_TUTOR   FOREIGN KEY (ID_TUTOR)   REFERENCES TB_TUTOR  (ID_TUTOR),
    CONSTRAINT FK_PET_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS TB_EVENTO_CLINICO (
    ID_EVENTO      BIGINT         NOT NULL DEFAULT nextval('SEQ_EVENTO_CLINICO'),
    TP_EVENTO      VARCHAR(50)    NOT NULL,
    DT_EVENTO      TIMESTAMP      NOT NULL,
    DS_DIAGNOSTICO VARCHAR(1000),
    DS_OBSERVACAO  VARCHAR(2000),
    ID_PET         BIGINT         NOT NULL,
    ID_CLINICA     BIGINT         NOT NULL,
    CONSTRAINT TB_EVENTO_CLINICO_PK PRIMARY KEY (ID_EVENTO),
    CONSTRAINT CK_EVENTO_TIPO       CHECK (TP_EVENTO IN ('CIRURGIA','CONSULTA','EXAME','RETORNO')),
    CONSTRAINT FK_EVENTO_PET        FOREIGN KEY (ID_PET)     REFERENCES TB_PET    (ID_PET),
    CONSTRAINT FK_EVENTO_CLINICA    FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS TB_PROTOCOLO_PREVENTIVO (
    ID_PROTOCOLO BIGINT        NOT NULL DEFAULT nextval('SEQ_PROTOCOLO'),
    TP_PROTOCOLO VARCHAR(50)   NOT NULL,
    NM_PROTOCOLO VARCHAR(200)  NOT NULL,
    DT_APLICACAO TIMESTAMP,
    DT_PROXIMA   TIMESTAMP,
    ST_STATUS    VARCHAR(20)   NOT NULL,
    ID_PET       BIGINT        NOT NULL,
    CONSTRAINT TB_PROTOCOLO_PREVENTIVO_PK PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_PROT_TIPO               CHECK (TP_PROTOCOLO IN ('ANTIPULGA','CHECKUP','VACINA','VERMIFUGO')),
    CONSTRAINT CK_PROT_STATUS             CHECK (ST_STATUS    IN ('ATRASADO','PENDENTE','REALIZADO')),
    CONSTRAINT FK_PROT_PET                FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE IF NOT EXISTS TB_MEDICAMENTO (
    ID_MEDICAMENTO BIGINT        NOT NULL DEFAULT nextval('SEQ_MEDICAMENTO'),
    NM_MEDICAMENTO VARCHAR(200)  NOT NULL,
    DS_DOSAGEM     VARCHAR(100)  NOT NULL,
    DS_FREQUENCIA  VARCHAR(100)  NOT NULL,
    DT_INICIO      TIMESTAMP     NOT NULL,
    DT_FIM         TIMESTAMP,
    ID_EVENTO      BIGINT        NOT NULL,
    CONSTRAINT TB_MEDICAMENTO_PK PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MED_EVENTO     FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO_CLINICO (ID_EVENTO)
);

CREATE TABLE IF NOT EXISTS TB_ADESAO_MEDICAMENTO (
    ID_ADESAO      BIGINT       NOT NULL DEFAULT nextval('SEQ_ADESAO'),
    DT_DOSE        TIMESTAMP    NOT NULL,
    ST_TOMOU       CHAR(1)      NOT NULL,
    DS_OBSERVACAO  VARCHAR(500),
    ID_MEDICAMENTO BIGINT       NOT NULL,
    CONSTRAINT TB_ADESAO_MEDICAMENTO_PK PRIMARY KEY (ID_ADESAO),
    CONSTRAINT CK_ADESAO_TOMOU          CHECK (ST_TOMOU IN ('N','S')),
    CONSTRAINT FK_ADESAO_MED            FOREIGN KEY (ID_MEDICAMENTO) REFERENCES TB_MEDICAMENTO (ID_MEDICAMENTO)
);

CREATE TABLE IF NOT EXISTS TB_NOTIFICACAO (
    ID_NOTIFICACAO BIGINT        NOT NULL DEFAULT nextval('SEQ_NOTIFICACAO'),
    TP_NOTIFICACAO VARCHAR(50)   NOT NULL,
    DS_TITULO      VARCHAR(200)  NOT NULL,
    DS_MENSAGEM    VARCHAR(2000),
    DT_ENVIO       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ST_LIDA        CHAR(1)       NOT NULL,
    ID_TUTOR       BIGINT        NOT NULL,
    ID_PET         BIGINT        NOT NULL,
    CONSTRAINT TB_NOTIFICACAO_PK  PRIMARY KEY (ID_NOTIFICACAO),
    CONSTRAINT CK_NOTIF_TIPO      CHECK (TP_NOTIFICACAO IN ('ALERTA','INFO','LEMBRETE','URGENTE')),
    CONSTRAINT CK_NOTIF_LIDA      CHECK (ST_LIDA        IN ('N','S')),
    CONSTRAINT FK_NOTIF_TUTOR     FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR (ID_TUTOR),
    CONSTRAINT FK_NOTIF_PET       FOREIGN KEY (ID_PET)   REFERENCES TB_PET   (ID_PET)
);

CREATE TABLE IF NOT EXISTS TB_SCORE_HISTORICO (
    ID_SCORE      BIGINT      NOT NULL DEFAULT nextval('SEQ_SCORE_HIST'),
    NR_SCORE      NUMERIC(5,2) NOT NULL,
    DT_REGISTRO   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DS_OBSERVACAO VARCHAR(500),
    ID_PET        BIGINT      NOT NULL,
    CONSTRAINT TB_SCORE_HISTORICO_PK PRIMARY KEY (ID_SCORE),
    CONSTRAINT CK_SCORE_VALOR        CHECK (NR_SCORE BETWEEN 0 AND 100),
    CONSTRAINT FK_SCORE_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE IF NOT EXISTS TB_BCS_HISTORICO (
    ID_BCS        BIGINT         NOT NULL DEFAULT nextval('SEQ_BCS_HIST'),
    NR_BCS        NUMERIC(2,0),
    DS_FOTO_URL   VARCHAR(500),
    DS_OBSERVACAO VARCHAR(1000),
    DT_ANALISE    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ID_PET        BIGINT         NOT NULL,
    CONSTRAINT TB_BCS_HISTORICO_PK PRIMARY KEY (ID_BCS),
    CONSTRAINT CK_BCS_VALOR        CHECK (NR_BCS BETWEEN 1 AND 9),
    CONSTRAINT FK_BCS_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE IF NOT EXISTS TB_COLLAR_LEITURA (
    ID_LEITURA     BIGINT       NOT NULL DEFAULT nextval('SEQ_COLLAR'),
    NR_TEMPERATURA NUMERIC(5,2) NOT NULL,
    NR_ATIVIDADE   NUMERIC(6,2),
    DT_LEITURA     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DS_TOPICO_MQTT VARCHAR(200),
    ID_PET         BIGINT       NOT NULL,
    CONSTRAINT TB_COLLAR_LEITURA_PK PRIMARY KEY (ID_LEITURA),
    CONSTRAINT CK_COLLAR_TEMP       CHECK (NR_TEMPERATURA BETWEEN 30 AND 45),
    CONSTRAINT FK_COLLAR_PET        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE IF NOT EXISTS TB_ALERTA (
    ID_ALERTA    BIGINT         NOT NULL DEFAULT nextval('SEQ_ALERTA'),
    TP_ALERTA    VARCHAR(50)    NOT NULL,
    DS_DESCRICAO VARCHAR(1000),
    NR_VALOR_REF NUMERIC(8,2),
    DT_ALERTA    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ST_RESOLVIDO CHAR(1)        NOT NULL,
    ID_PET       BIGINT         NOT NULL,
    CONSTRAINT TB_ALERTA_PK        PRIMARY KEY (ID_ALERTA),
    CONSTRAINT CK_ALERTA_TIPO      CHECK (TP_ALERTA    IN ('ADESAO','BCS_CRITICO','FEBRE','PESO','SEDENTARISMO')),
    CONSTRAINT CK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('N','S')),
    CONSTRAINT FK_ALERTA_PET       FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);
