-- =============================================================================
-- V1: DDL ESTRUTURAL DO PETTRACK (Oracle Database)
-- =============================================================================

-- Sequences
CREATE SEQUENCE SEQ_TUTOR          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLINICA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROTOCOLO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAMENTO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADESAO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTIFICACAO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SCORE_HIST     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BCS_HIST       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COLLAR         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOG_ERRO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Logs de Erro
CREATE TABLE TB_LOG_ERRO (
    ID_LOG        NUMBER         NOT NULL,
    NM_PROCEDURE  VARCHAR2(100)  NOT NULL,
    NM_USUARIO    VARCHAR2(100)  NOT NULL,
    DT_OCORRENCIA DATE           DEFAULT SYSDATE NOT NULL,
    CD_ERRO       NUMBER         NOT NULL,
    DS_MENSAGEM   VARCHAR2(4000),
    CONSTRAINT TB_LOG_ERRO_PK PRIMARY KEY (ID_LOG)
);

-- Tabela de Tutores
CREATE TABLE TB_TUTOR (
    ID_TUTOR    NUMBER         NOT NULL,
    NM_TUTOR    VARCHAR2(150)  NOT NULL,
    DS_EMAIL    VARCHAR2(200)  NOT NULL,
    NR_TELEFONE VARCHAR2(20),
    DS_ENDERECO VARCHAR2(300),
    DT_CADASTRO DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TB_TUTOR_PK       PRIMARY KEY (ID_TUTOR),
    CONSTRAINT TB_TUTOR_EMAIL_UN UNIQUE      (DS_EMAIL)
);

-- Tabela de Clínicas
CREATE TABLE TB_CLINICA (
    ID_CLINICA  NUMBER         NOT NULL,
    NM_CLINICA  VARCHAR2(200)  NOT NULL,
    NR_CNPJ     VARCHAR2(18)   NOT NULL,
    DS_EMAIL    VARCHAR2(200),
    NR_TELEFONE VARCHAR2(20),
    DS_ENDERECO VARCHAR2(300),
    DT_CADASTRO DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TB_CLINICA_PK      PRIMARY KEY (ID_CLINICA),
    CONSTRAINT TB_CLINICA_CNPJ_UN UNIQUE      (NR_CNPJ)
);

-- Tabela de Pets
CREATE TABLE TB_PET (
    ID_PET        NUMBER        NOT NULL,
    NM_PET        VARCHAR2(100) NOT NULL,
    DS_ESPECIE    VARCHAR2(50)  NOT NULL,
    DS_RACA       VARCHAR2(100),
    DS_SEXO       CHAR(1),
    NR_IDADE_ANOS NUMBER(3,1),
    NR_PESO_KG    NUMBER(6,3),
    DT_CADASTRO   DATE          DEFAULT SYSDATE NOT NULL,
    ID_TUTOR      NUMBER        NOT NULL,
    ID_CLINICA    NUMBER        NOT NULL,
    CONSTRAINT TB_PET_PK      PRIMARY KEY (ID_PET),
    CONSTRAINT CK_PET_SEXO    CHECK (DS_SEXO IN ('F','M')),
    CONSTRAINT FK_PET_TUTOR   FOREIGN KEY (ID_TUTOR)   REFERENCES TB_TUTOR  (ID_TUTOR),
    CONSTRAINT FK_PET_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

-- Tabela de Eventos Clínicos
CREATE TABLE TB_EVENTO_CLINICO (
    ID_EVENTO      NUMBER         NOT NULL,
    TP_EVENTO      VARCHAR2(50)   NOT NULL,
    DT_EVENTO      DATE           NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(1000),
    DS_OBSERVACAO  VARCHAR2(2000),
    ID_PET         NUMBER         NOT NULL,
    ID_CLINICA     NUMBER         NOT NULL,
    CONSTRAINT TB_EVENTO_CLINICO_PK PRIMARY KEY (ID_EVENTO),
    CONSTRAINT CK_EVENTO_TIPO       CHECK (TP_EVENTO IN ('CIRURGIA','CONSULTA','EXAME','RETORNO')),
    CONSTRAINT FK_EVENTO_PET        FOREIGN KEY (ID_PET)     REFERENCES TB_PET    (ID_PET),
    CONSTRAINT FK_EVENTO_CLINICA    FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

-- Tabela de Protocolos Preventivos
CREATE TABLE TB_PROTOCOLO_PREVENTIVO (
    ID_PROTOCOLO NUMBER        NOT NULL,
    TP_PROTOCOLO VARCHAR2(50)  NOT NULL,
    NM_PROTOCOLO VARCHAR2(200) NOT NULL,
    DT_APLICACAO DATE,
    DT_PROXIMA   DATE,
    ST_STATUS    VARCHAR2(20)  NOT NULL,
    ID_PET       NUMBER        NOT NULL,
    CONSTRAINT TB_PROTOCOLO_PREVENTIVO_PK PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_PROT_TIPO               CHECK (TP_PROTOCOLO IN ('ANTIPULGA','CHECKUP','VACINA','VERMIFUGO')),
    CONSTRAINT CK_PROT_STATUS             CHECK (ST_STATUS    IN ('ATRASADO','PENDENTE','REALIZADO')),
    CONSTRAINT FK_PROT_PET                FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

-- Tabela de Medicamentos
CREATE TABLE TB_MEDICAMENTO (
    ID_MEDICAMENTO NUMBER        NOT NULL,
    NM_MEDICAMENTO VARCHAR2(200) NOT NULL,
    DS_DOSAGEM     VARCHAR2(100) NOT NULL,
    DS_FREQUENCIA  VARCHAR2(100) NOT NULL,
    DT_INICIO      DATE          NOT NULL,
    DT_FIM         DATE,
    ID_EVENTO      NUMBER        NOT NULL,
    CONSTRAINT TB_MEDICAMENTO_PK PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MED_EVENTO     FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO_CLINICO (ID_EVENTO)
);

-- Tabela de Adesão Medicamentosa
CREATE TABLE TB_ADESAO_MEDICAMENTO (
    ID_ADESAO      NUMBER       NOT NULL,
    DT_DOSE        DATE         NOT NULL,
    ST_TOMOU       CHAR(1)      NOT NULL,
    DS_OBSERVACAO  VARCHAR2(500),
    ID_MEDICAMENTO NUMBER       NOT NULL,
    CONSTRAINT TB_ADESAO_MEDICAMENTO_PK PRIMARY KEY (ID_ADESAO),
    CONSTRAINT CK_ADESAO_TOMOU          CHECK (ST_TOMOU IN ('N','S')),
    CONSTRAINT FK_ADESAO_MED            FOREIGN KEY (ID_MEDICAMENTO) REFERENCES TB_MEDICAMENTO (ID_MEDICAMENTO)
);

-- Tabela de Notificações
CREATE TABLE TB_NOTIFICACAO (
    ID_NOTIFICACAO NUMBER        NOT NULL,
    TP_NOTIFICACAO VARCHAR2(50)  NOT NULL,
    DS_TITULO      VARCHAR2(200) NOT NULL,
    DS_MENSAGEM    VARCHAR2(2000),
    DT_ENVIO       DATE          DEFAULT SYSDATE NOT NULL,
    ST_LIDA        CHAR(1)       NOT NULL,
    ID_TUTOR       NUMBER        NOT NULL,
    ID_PET         NUMBER        NOT NULL,
    CONSTRAINT TB_NOTIFICACAO_PK  PRIMARY KEY (ID_NOTIFICACAO),
    CONSTRAINT CK_NOTIF_TIPO      CHECK (TP_NOTIFICACAO IN ('ALERTA','INFO','LEMBRETE','URGENTE')),
    CONSTRAINT CK_NOTIF_LIDA      CHECK (ST_LIDA        IN ('N','S')),
    CONSTRAINT FK_NOTIF_TUTOR     FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR (ID_TUTOR),
    CONSTRAINT FK_NOTIF_PET       FOREIGN KEY (ID_PET)   REFERENCES TB_PET   (ID_PET)
);

-- Tabela de Health Score Histórico
CREATE TABLE TB_SCORE_HISTORICO (
    ID_SCORE      NUMBER      NOT NULL,
    NR_SCORE      NUMBER(5,2) NOT NULL,
    DT_REGISTRO   DATE        DEFAULT SYSDATE NOT NULL,
    DS_OBSERVACAO VARCHAR2(500),
    ID_PET        NUMBER      NOT NULL,
    CONSTRAINT TB_SCORE_HISTORICO_PK PRIMARY KEY (ID_SCORE),
    CONSTRAINT CK_SCORE_VALOR        CHECK (NR_SCORE BETWEEN 0 AND 100),
    CONSTRAINT FK_SCORE_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

-- Tabela de BCS (Body Condition Score)
CREATE TABLE TB_BCS_HISTORICO (
    ID_BCS        NUMBER         NOT NULL,
    NR_BCS        NUMBER(2),
    DS_FOTO_URL   VARCHAR2(500),
    DS_OBSERVACAO VARCHAR2(1000),
    DT_ANALISE    DATE           DEFAULT SYSDATE NOT NULL,
    ID_PET        NUMBER         NOT NULL,
    CONSTRAINT TB_BCS_HISTORICO_PK PRIMARY KEY (ID_BCS),
    CONSTRAINT CK_BCS_VALOR        CHECK (NR_BCS BETWEEN 1 AND 9),
    CONSTRAINT FK_BCS_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

-- Tabela de Leituras IoT do Colar Inteligente
CREATE TABLE TB_COLLAR_LEITURA (
    ID_LEITURA     NUMBER      NOT NULL,
    NR_TEMPERATURA NUMBER(5,2) NOT NULL,
    NR_ATIVIDADE   NUMBER(6,2),
    DT_LEITURA     DATE        DEFAULT SYSDATE NOT NULL,
    DS_TOPICO_MQTT VARCHAR2(200),
    ID_PET         NUMBER      NOT NULL,
    CONSTRAINT TB_COLLAR_LEITURA_PK PRIMARY KEY (ID_LEITURA),
    CONSTRAINT CK_COLLAR_TEMP       CHECK (NR_TEMPERATURA BETWEEN 30 AND 45),
    CONSTRAINT FK_COLLAR_PET        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

-- Tabela de Alertas Clínicos
CREATE TABLE TB_ALERTA (
    ID_ALERTA    NUMBER         NOT NULL,
    TP_ALERTA    VARCHAR2(50)   NOT NULL,
    DS_DESCRICAO VARCHAR2(1000),
    NR_VALOR_REF NUMBER(8,2),
    DT_ALERTA    DATE           DEFAULT SYSDATE NOT NULL,
    ST_RESOLVIDO CHAR(1)        NOT NULL,
    ID_PET       NUMBER         NOT NULL,
    CONSTRAINT TB_ALERTA_PK        PRIMARY KEY (ID_ALERTA),
    CONSTRAINT CK_ALERTA_TIPO      CHECK (TP_ALERTA    IN ('ADESAO','BCS_CRITICO','FEBRE','PESO','SEDENTARISMO')),
    CONSTRAINT CK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('N','S')),
    CONSTRAINT FK_ALERTA_PET       FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);
