CREATE SEQUENCE IF NOT EXISTS SEQ_USUARIO START WITH 1 INCREMENT BY 1;
DROP TABLE IF EXISTS TB_USUARIO CASCADE;
CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID_USUARIO BIGINT       NOT NULL DEFAULT nextval('SEQ_USUARIO'),
    NM_NOME    VARCHAR(150) NOT NULL,
    DS_EMAIL   VARCHAR(200) NOT NULL,
    DS_SENHA   VARCHAR(255) NOT NULL,
    DS_ROLE    VARCHAR(50)  NOT NULL,
    ST_ATIVO   CHAR(1)      NOT NULL DEFAULT 'S',
    ID_TUTOR   BIGINT,
    ID_CLINICA BIGINT,
    CONSTRAINT TB_USUARIO_PK       PRIMARY KEY (ID_USUARIO),
    CONSTRAINT TB_USUARIO_EMAIL_UN UNIQUE (DS_EMAIL),
    CONSTRAINT CK_USUARIO_ROLE     CHECK (DS_ROLE IN ('ROLE_ADMIN', 'ROLE_VET', 'ROLE_TUTOR')),
    CONSTRAINT CK_USUARIO_ATIVO    CHECK (ST_ATIVO IN ('N', 'S')),
    CONSTRAINT FK_USUARIO_TUTOR    FOREIGN KEY (ID_TUTOR)   REFERENCES TB_TUTOR  (ID_TUTOR),
    CONSTRAINT FK_USUARIO_CLINICA  FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);