INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
SELECT nextval('SEQ_CLINICA'), 'VetLife Clínica Veterinária', '758748948123958473', 'vetlife@gmail.com', '11986758764', 'Rua Gamelinha, 99', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TB_CLINICA WHERE NR_CNPJ = '758748948123958473');

INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
SELECT nextval('SEQ_CLINICA'), 'PetCare Hospital Animal', '455874764815675783', 'petcare@gmail.com', '11945758765', 'Rua Alfredo, 143', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TB_CLINICA WHERE NR_CNPJ = '455874764815675783');

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
SELECT nextval('SEQ_TUTOR'), 'Ana Paula Silva', 'ana.silva@icloud.com', '11975647387', 'Rua José, 89', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TB_TUTOR WHERE DS_EMAIL = 'ana.silva@icloud.com');

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
SELECT nextval('SEQ_TUTOR'), 'Carlos Eduardo Santos', 'carlos.santos@icloud.com', '11938768576', 'Rua Pedro de Souza, 56', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TB_TUTOR WHERE DS_EMAIL = 'carlos.santos@icloud.com');

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO)
SELECT nextval('SEQ_USUARIO'), 'Administrador PetTrack', 'admin@pettrack.com', '.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_ADMIN', 'S'
WHERE NOT EXISTS (SELECT 1 FROM TB_USUARIO WHERE DS_EMAIL = 'admin@pettrack.com');

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_CLINICA)
SELECT nextval('SEQ_USUARIO'), 'Dra. Camila Veterinária', 'vet@pettrack.com', '.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_VET', 'S', 1
WHERE NOT EXISTS (SELECT 1 FROM TB_USUARIO WHERE DS_EMAIL = 'vet@pettrack.com');

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR)
SELECT nextval('SEQ_USUARIO'), 'Ana Paula Silva (Tutor)', 'ana.silva@icloud.com', '.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_TUTOR', 'S', 1
WHERE NOT EXISTS (SELECT 1 FROM TB_USUARIO WHERE DS_EMAIL = 'ana.silva@icloud.com');

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR)
SELECT nextval('SEQ_USUARIO'), 'Carlos Eduardo (Tutor)', 'carlos.santos@icloud.com', '.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_TUTOR', 'S', 2
WHERE NOT EXISTS (SELECT 1 FROM TB_USUARIO WHERE DS_EMAIL = 'carlos.santos@icloud.com');
