-- =============================================================================
-- V3: CARGA DE DADOS INICIAIS E USUÁRIOS DO SISTEMA
-- =============================================================================

-- 1. Clínicas Veterinárias
INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_CLINICA.NEXTVAL, 'VetLife Clínica Veterinária', '758748948123958473', 'vetlife@gmail.com', '11986758764', 'Rua Gamelinha, 99', SYSDATE);

INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_CLINICA.NEXTVAL, 'PetCare Hospital Animal', '455874764815675783', 'petcare@gmail.com', '11945758765', 'Rua Alfredo, 143', SYSDATE);

INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_CLINICA.NEXTVAL, 'Animal Center Veterinária', '12345678000101', 'animalcenter@gmail.com', '11988887777', 'Rua Augusta, 250', SYSDATE);

INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_CLINICA.NEXTVAL, 'Pet Saúde Hospital', '23456789000102', 'petsaude@gmail.com', '11977776666', 'Av Paulista, 1000', SYSDATE);

INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_CLINICA.NEXTVAL, 'Hospital Vet Mais', '34567890000103', 'vetmais@gmail.com', '11966665555', 'Rua Vergueiro, 500', SYSDATE);

-- 2. Tutores
INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_TUTOR.NEXTVAL, 'Ana Paula Silva', 'ana.silva@icloud.com', '11975647387', 'Rua José, 89', SYSDATE);

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_TUTOR.NEXTVAL, 'Carlos Eduardo Santos', 'carlos.santos@icloud.com', '11938768576', 'Rua Pedro de Souza, 56', SYSDATE);

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_TUTOR.NEXTVAL, 'Mariana Oliveira', 'mariana.oli@icloud.com', '11986758744', 'Rua José Mourinho, 59', SYSDATE);

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_TUTOR.NEXTVAL, 'João Pedro Almeida', 'joao.almeida@gmail.com', '11955554444', 'Rua Consolação, 120', SYSDATE);

INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO, DT_CADASTRO)
VALUES (SEQ_TUTOR.NEXTVAL, 'Beatriz Martins', 'beatriz.martins@gmail.com', '11944443333', 'Rua Haddock Lobo, 300', SYSDATE);

-- 3. Pets
INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, DT_CADASTRO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_PET.NEXTVAL, 'Thor', 'Cão', 'Golden Retriever', 'M', 8.0, 32.500, SYSDATE, 1, 1);

INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, DT_CADASTRO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_PET.NEXTVAL, 'Luna', 'Gato', 'Persa', 'F', 5.0, 4.200, SYSDATE, 2, 1);

INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, DT_CADASTRO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_PET.NEXTVAL, 'Bob', 'Cão', 'Bulldog', 'M', 6.0, 14.800, SYSDATE, 3, 2);

INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, DT_CADASTRO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_PET.NEXTVAL, 'Nina', 'Cão', 'SRD', 'F', 3.0, 9.500, SYSDATE, 4, 2);

INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, DT_CADASTRO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_PET.NEXTVAL, 'Max', 'Cão', 'Labrador', 'M', 4.0, 28.000, SYSDATE, 5, 3);

-- 4. Eventos Clínicos
INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'CONSULTA', TO_DATE('10/01/2025', 'DD/MM/YYYY'), 'Dermatite alérgica', 'Coceira intensa', 1, 1);

INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'EXAME', TO_DATE('15/01/2025', 'DD/MM/YYYY'), 'Hemograma completo', 'Rotina anual', 2, 1);

INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'RETORNO', TO_DATE('20/01/2025', 'DD/MM/YYYY'), 'Melhora do quadro', 'Manter medicação', 3, 2);

INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'CIRURGIA', TO_DATE('05/02/2025', 'DD/MM/YYYY'), 'Castração Eletiva', 'Sem intercorrências', 4, 2);

INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'CONSULTA', TO_DATE('10/02/2025', 'DD/MM/YYYY'), 'Avaliação Nutricional', 'Dieta prescrita', 5, 3);

INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA)
VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, 'CONSULTA', TO_DATE('28/02/2025', 'DD/MM/YYYY'), 'Boa recuperação', 'Alta médica', 3, 1);

-- 5. Protocolos Preventivos
INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'VACINA', 'V10 Polivalente', TO_DATE('05/01/2025', 'DD/MM/YYYY'), TO_DATE('05/01/2026', 'DD/MM/YYYY'), 'REALIZADO', 1);

INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'VERMIFUGO', 'Drontal Plus', TO_DATE('05/02/2025', 'DD/MM/YYYY'), TO_DATE('05/05/2026', 'DD/MM/YYYY'), 'REALIZADO', 2);

INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'VACINA', 'Antirrábica', TO_DATE('10/01/2025', 'DD/MM/YYYY'), TO_DATE('01/03/2025', 'DD/MM/YYYY'), 'REALIZADO', 3);

INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'CHECKUP', 'Checkup Plus', TO_DATE('01/04/2025', 'DD/MM/YYYY'), TO_DATE('01/09/2025', 'DD/MM/YYYY'), 'REALIZADO', 4);

INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'ANTIPULGA', 'Frontline', TO_DATE('10/02/2025', 'DD/MM/YYYY'), TO_DATE('10/05/2025', 'DD/MM/YYYY'), 'ATRASADO', 5);

INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
VALUES (SEQ_PROTOCOLO.NEXTVAL, 'VACINA', 'V10 Polivalente', NULL, TO_DATE('15/04/2025', 'DD/MM/YYYY'), 'PENDENTE', 4);

-- 6. Medicamentos
INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Apoquel 16mg', '1 comprimido', '1x ao dia', TO_DATE('10/01/2025', 'DD/MM/YYYY'), TO_DATE('10/02/2025', 'DD/MM/YYYY'), 1);

INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Gaviz V 10mg', '1 comprimido', '1x ao dia', TO_DATE('15/01/2025', 'DD/MM/YYYY'), TO_DATE('30/01/2025', 'DD/MM/YYYY'), 2);

INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Prednisolona 5mg', '1 comprimido', '2x ao dia', TO_DATE('15/02/2025', 'DD/MM/YYYY'), TO_DATE('15/03/2025', 'DD/MM/YYYY'), 3);

INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Royal Canin Satiety', '1 sachê', '2x ao dia', TO_DATE('20/01/2025', 'DD/MM/YYYY'), TO_DATE('27/01/2025', 'DD/MM/YYYY'), 4);

INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Vermífugo Plus', '1 comprimido', 'Dose única', TO_DATE('05/03/2025', 'DD/MM/YYYY'), TO_DATE('05/03/2025', 'DD/MM/YYYY'), 5);

INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO)
VALUES (SEQ_MEDICAMENTO.NEXTVAL, 'Tramadol 50mg', '1 comprimido', '3x ao dia', TO_DATE('28/02/2025', 'DD/MM/YYYY'), TO_DATE('05/03/2025', 'DD/MM/YYYY'), 6);

-- 7. Adesão Medicamentosa
INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('11/01/2025', 'DD/MM/YYYY'), 'S', NULL, 1);

INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('16/01/2025', 'DD/MM/YYYY'), 'S', NULL, 2);

INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('17/02/2025', 'DD/MM/YYYY'), 'N', 'Tutor esqueceu a dose', 3);

INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('21/01/2025', 'DD/MM/YYYY'), 'S', NULL, 4);

INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('06/03/2025', 'DD/MM/YYYY'), 'S', NULL, 5);

INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO)
VALUES (SEQ_ADESAO.NEXTVAL, TO_DATE('01/03/2025', 'DD/MM/YYYY'), 'S', NULL, 6);

-- 8. Notificações
INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'LEMBRETE', 'Vacina do Thor', 'Lembrete: vacina V10 vence em breve', SYSDATE, 'N', 1, 1);

INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'ALERTA', 'Febre detectada - Luna', 'Temperatura acima do normal', SYSDATE, 'N', 2, 2);

INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'URGENTE', 'Medicamento pendente - Bob', 'Dose não confirmada hoje', SYSDATE, 'N', 3, 3);

INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'INFO', 'Consulta realizada - Nina', 'Castração realizada com sucesso', SYSDATE, 'S', 4, 4);

INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'LEMBRETE', 'Antipulga atrasado - Max', 'Aplicação está atrasada', SYSDATE, 'N', 5, 5);

-- 9. Histórico de Score de Saúde
INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
VALUES (SEQ_SCORE_HIST.NEXTVAL, 75.00, SYSDATE, 'Score inicial', 1);

INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
VALUES (SEQ_SCORE_HIST.NEXTVAL, 82.00, SYSDATE, 'Recuperado', 1);

INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
VALUES (SEQ_SCORE_HIST.NEXTVAL, 60.00, SYSDATE, 'Score inicial', 2);

INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
VALUES (SEQ_SCORE_HIST.NEXTVAL, 63.00, SYSDATE, 'Evoluindo bem', 2);

INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
VALUES (SEQ_SCORE_HIST.NEXTVAL, 80.00, SYSDATE, 'Score inicial', 3);

-- 10. Escore Corporal (BCS)
INSERT INTO TB_BCS_HISTORICO (ID_BCS, NR_BCS, DS_FOTO_URL, DS_OBSERVACAO, DT_ANALISE, ID_PET)
VALUES (SEQ_BCS_HIST.NEXTVAL, 5, 'http://pettrack.com/fotos/thor1.jpg', 'BCS ideal', 1);

INSERT INTO TB_BCS_HISTORICO (ID_BCS, NR_BCS, DS_FOTO_URL, DS_OBSERVACAO, DT_ANALISE, ID_PET)
VALUES (SEQ_BCS_HIST.NEXTVAL, 7, 'http://pettrack.com/fotos/luna1.jpg', 'Acima do ideal', 2);

INSERT INTO TB_BCS_HISTORICO (ID_BCS, NR_BCS, DS_FOTO_URL, DS_OBSERVACAO, DT_ANALISE, ID_PET)
VALUES (SEQ_BCS_HIST.NEXTVAL, 4, 'http://pettrack.com/fotos/bob1.jpg', 'Levemente abaixo', 3);

-- 11. Leituras IoT do Colar
INSERT INTO TB_COLLAR_LEITURA (ID_LEITURA, NR_TEMPERATURA, NR_ATIVIDADE, DT_LEITURA, DS_TOPICO_MQTT, ID_PET)
VALUES (SEQ_COLLAR.NEXTVAL, 38.50, 120.00, SYSDATE, 'pettrack/collar/pet1', 1);

INSERT INTO TB_COLLAR_LEITURA (ID_LEITURA, NR_TEMPERATURA, NR_ATIVIDADE, DT_LEITURA, DS_TOPICO_MQTT, ID_PET)
VALUES (SEQ_COLLAR.NEXTVAL, 39.80, 30.00, SYSDATE, 'pettrack/collar/pet2', 2);

INSERT INTO TB_COLLAR_LEITURA (ID_LEITURA, NR_TEMPERATURA, NR_ATIVIDADE, DT_LEITURA, DS_TOPICO_MQTT, ID_PET)
VALUES (SEQ_COLLAR.NEXTVAL, 38.20, 95.00, SYSDATE, 'pettrack/collar/pet3', 3);

-- 12. Alertas Clínicos
INSERT INTO TB_ALERTA (ID_ALERTA, TP_ALERTA, DS_DESCRICAO, NR_VALOR_REF, DT_ALERTA, ST_RESOLVIDO, ID_PET)
VALUES (SEQ_ALERTA.NEXTVAL, 'FEBRE', 'Temperatura acima de 39.5C', 39.80, SYSDATE, 'N', 2);

INSERT INTO TB_ALERTA (ID_ALERTA, TP_ALERTA, DS_DESCRICAO, NR_VALOR_REF, DT_ALERTA, ST_RESOLVIDO, ID_PET)
VALUES (SEQ_ALERTA.NEXTVAL, 'FEBRE', 'Temperatura elevada detectada', 40.10, SYSDATE, 'N', 4);

INSERT INTO TB_ALERTA (ID_ALERTA, TP_ALERTA, DS_DESCRICAO, NR_VALOR_REF, DT_ALERTA, ST_RESOLVIDO, ID_PET)
VALUES (SEQ_ALERTA.NEXTVAL, 'SEDENTARISMO', 'Atividade abaixo do esperado', 10.00, SYSDATE, 'N', 4);

-- 13. Usuários do Sistema para Spring Security
-- Senhas criptografadas com BCrypt:
-- admin@pettrack.com / admin123 -> $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
-- vet@pettrack.com   / vet123   -> $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
-- tutor@pettrack.com / tutor123 -> $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_USUARIO.NEXTVAL, 'Administrador PetTrack', 'admin@pettrack.com', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_ADMIN', 'S', NULL, NULL);

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_USUARIO.NEXTVAL, 'Dra. Camila Veterinária', 'vet@pettrack.com', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_VET', 'S', NULL, 1);

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_USUARIO.NEXTVAL, 'Ana Paula Silva (Tutor)', 'ana.silva@icloud.com', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_TUTOR', 'S', 1, NULL);

INSERT INTO TB_USUARIO (ID_USUARIO, NM_NOME, DS_EMAIL, DS_SENHA, DS_ROLE, ST_ATIVO, ID_TUTOR, ID_CLINICA)
VALUES (SEQ_USUARIO.NEXTVAL, 'Carlos Eduardo (Tutor)', 'carlos.santos@icloud.com', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'ROLE_TUTOR', 'S', 2, NULL);
